services:
#    bvi_file_upload.example:
#        class: Bvi\FileUploadBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

     bvi.helper.upload:
       class: Bvi\FileUploadBundle\Helper\UploadHelper
       arguments: 
          container : "@service_container"
